### ISSUE TITLE
Support for 7.5 inch?

### ISSUE THREAD

**Issue by rasben** [hdeiner/E-Paper-Calendar#1]
Hello :)

Does this project also work with a 7.5 inch 800x480 screen?

**Comment by hdeiner** [comment]
No.  A couple of things.

First, the graphics are presuming the 1024x800 (IIRC, since waveshare no longer seems to sell the product.  You could scale all of the x,y, and length values to fit.  Or do it smarter.

Also, in line 406 of E-Paper.py, the call os.system('sudo /home/pi/E-Paper-Calendar/Calendar/Driver-files/IT8951/IT8951 0 0 /home/pi/E-Paper-Calendar/Calendar/current-image.bmp') would definitely have to change to the specific driver supplied by the epaper vendor to write the image to the epaper device.

Sorry about that.

--  howard

**Comment by rasben** [comment]
Dont apologise! I was just asking :)

Thank you so much for answering so quickly. 
I'll close the issue.
